package relay

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

// MobilityClass defines how a run can be moved between workers.
type MobilityClass string

const (
	MobilityPinned    MobilityClass = "pinned"
	MobilityResumable MobilityClass = "resumable"
	MobilityCloneable MobilityClass = "cloneable"
	MobilityEphemeral MobilityClass = "ephemeral"
)

// ValidMobilityClasses is the set of recognized mobility classes.
var ValidMobilityClasses = map[MobilityClass]bool{
	MobilityPinned:    true,
	MobilityResumable: true,
	MobilityCloneable: true,
	MobilityEphemeral: true,
}

var validSourceTypes = map[string]bool{
	"api":    true,
	"cron":   true,
	"github": true,
	"linear": true,
	"slack":  true,
}

var validWorkspaceModes = map[string]bool{
	"local":     true,
	"worktree":  true,
	"container": true,
	"vm":        true,
	"sandbox":   true,
}

var validOutputTypes = map[string]bool{
	"artifact": true,
	"approval": true,
	"comment":  true,
	"patch":    true,
	"pr":       true,
	"summary":  true,
}

// OutputExpectation describes what the run should produce.
type OutputExpectation struct {
	Type   string `json:"type"`             // "patch", "pr", "comment", "summary", "artifact", "approval"
	Format string `json:"format,omitempty"` // "diff", "markdown", "text", "json"
	Target string `json:"target,omitempty"` // "github:pr", "slack:reply", "linear:update"
}

// TriggerSource identifies where the run request came from.
type TriggerSource struct {
	Type      string `json:"type"`       // "github", "slack", "linear", "api", "cron"
	TriggerID string `json:"trigger_id"` // webhook delivery ID or event ID
	ThreadID  string `json:"thread_id"`  // deterministic external thread ID
}

// WorkspaceTarget specifies where and how the workspace should be provisioned.
type WorkspaceTarget struct {
	Mode    string `json:"mode"` // "local", "worktree", "container", "vm", "sandbox"
	RepoURL string `json:"repo_url,omitempty"`
	Clean   bool   `json:"clean"` // true = provision fresh workspace
}

// RunLimits sets bounds on execution.
type RunLimits struct {
	MaxTurns       int `json:"max_turns,omitempty"`
	BudgetTokens   int `json:"budget_tokens,omitempty"`
	TimeoutSeconds int `json:"timeout_seconds,omitempty"`
}

// RunMetadata carries audit and operational metadata.
type RunMetadata struct {
	TenantID  string            `json:"tenant_id"`
	CreatedBy string            `json:"created_by"`
	CreatedAt time.Time         `json:"created_at"`
	Tags      []string          `json:"tags,omitempty"`
	Extra     map[string]string `json:"extra,omitempty"`
}

// RunContract is the complete specification of what to execute.
// It is the interface between Go Relay orchestration and go-code execution.
type RunContract struct {
	// ID is generated by Relay when the contract is composed.
	ID string `json:"id"`

	// Prompt is the task description / initial message.
	Prompt string `json:"prompt"`

	// Source identifies where this run request came from.
	Source TriggerSource `json:"source"`

	// Workspace specifies where and how the workspace should be provisioned.
	Workspace WorkspaceTarget `json:"workspace"`

	// Capabilities granted to this run.
	Capabilities CapabilityPack `json:"capabilities"`

	// Permissions defines what requires approval.
	Permissions PermissionSet `json:"permissions,omitempty"`

	// Limits sets bounds on execution.
	Limits RunLimits `json:"limits,omitempty"`

	// Outputs describes what the run should produce.
	Outputs []OutputExpectation `json:"outputs,omitempty"`

	// Mobility defines how the run can be moved between workers.
	Mobility MobilityClass `json:"mobility"`

	// Metadata carries audit and operational metadata.
	Metadata RunMetadata `json:"metadata"`

	// ContextHint is additional context injected from the trigger source.
	// This is bounded and may have truncation markers.
	ContextHint string `json:"context_hint,omitempty"`
}

// PermissionSet defines which tool actions require explicit approval.
type PermissionSet struct {
	ApprovalRequired []string `json:"approval_required,omitempty"` // e.g. "bash:destructive", "git:push"
	TrustTierMinimum string   `json:"trust_tier_minimum,omitempty"`
}

// Validate checks that the run contract has all required fields.
func (rc *RunContract) Validate() error {
	if strings.TrimSpace(rc.ID) == "" {
		return errors.New("run contract: id is required")
	}
	if strings.TrimSpace(rc.Prompt) == "" {
		return errors.New("run contract: prompt is required")
	}
	if strings.TrimSpace(rc.Metadata.TenantID) == "" {
		return errors.New("run contract: tenant_id is required")
	}
	if strings.TrimSpace(rc.Source.Type) == "" {
		rc.Source.Type = "api"
	}
	if !validSourceTypes[rc.Source.Type] {
		return fmt.Errorf("run contract: invalid source type %q", rc.Source.Type)
	}
	if strings.TrimSpace(rc.Workspace.Mode) == "" {
		rc.Workspace.Mode = "local"
	}
	if !validWorkspaceModes[rc.Workspace.Mode] {
		return fmt.Errorf("run contract: invalid workspace mode %q", rc.Workspace.Mode)
	}
	if rc.Mobility == "" {
		rc.Mobility = MobilityResumable
	}
	if !ValidMobilityClasses[rc.Mobility] {
		return fmt.Errorf("run contract: invalid mobility class %q", rc.Mobility)
	}
	if rc.Limits.MaxTurns < 0 || rc.Limits.BudgetTokens < 0 || rc.Limits.TimeoutSeconds < 0 {
		return errors.New("run contract: limits must be nonnegative")
	}
	for _, output := range rc.Outputs {
		if err := validateOutputExpectation(output); err != nil {
			return err
		}
	}
	if rc.Capabilities.hasEntries() {
		if strings.TrimSpace(rc.Capabilities.RunID) == "" {
			return errors.New("run contract: capability pack run_id is required when capabilities are present")
		}
		if rc.Capabilities.RunID != rc.ID {
			return fmt.Errorf("run contract: capability pack run_id %q does not match contract id %q", rc.Capabilities.RunID, rc.ID)
		}
	}
	if rc.Metadata.CreatedAt.IsZero() {
		rc.Metadata.CreatedAt = time.Now()
	}
	return nil
}

func validateOutputExpectation(output OutputExpectation) error {
	if strings.TrimSpace(output.Type) == "" {
		return errors.New("run contract: output type is required")
	}
	if validOutputTypes[output.Type] {
		return nil
	}
	parts := strings.Split(output.Type, ":")
	if len(parts) == 2 && parts[0] != "" && parts[1] != "" {
		return nil
	}
	return fmt.Errorf("run contract: invalid output type %q", output.Type)
}

func (cp CapabilityPack) hasEntries() bool {
	return len(cp.Tools) > 0 ||
		len(cp.MCPServers) > 0 ||
		len(cp.Memories) > 0 ||
		len(cp.Repos) > 0 ||
		len(cp.WorkspaceModes) > 0 ||
		len(cp.Secrets) > 0 ||
		len(cp.OutputSurfaces) > 0 ||
		cp.Browser != nil ||
		cp.Docker != nil
}

// ToJSON marshals the run contract to JSON.
func (rc *RunContract) ToJSON() ([]byte, error) {
	return json.Marshal(rc)
}

// RunContractFromJSON unmarshals a run contract from JSON.
func RunContractFromJSON(data []byte) (*RunContract, error) {
	rc := &RunContract{}
	if err := json.Unmarshal(data, rc); err != nil {
		return nil, fmt.Errorf("run contract: unmarshal: %w", err)
	}
	return rc, nil
}
